aplicaciones/empleados/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = "persona_app"

urlpatterns = [
    path('',views.InicioView.as_view(), name='inicio'),
    path('listar-todo-empleados/', views.ListAllEmpleados.as_view(), name='empleados_all'),
    path('listar-by-area/<shortname>', views.ListByAreaEmpleado.as_view(), name='empleados_area'),
    path('listar-empleados-admin/', views.ListaEmpleadosAdmin.as_view(), name='empleados_admin'),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('lista-habilidades-empleado/<id>', views.ListaHabilidadesEmpleado.as_view()),
    path('ver-empleado/<pk>', views.EmpleadoDetailView.as_view(),name='ver-empleado'),  #El <pk> es como el id, se usa para obtener el id unico para identificar el registro
    path('add-empleado/', views.EmpleadoCreateView.as_view(), name='empleado_add'),
    path('success/', views.SuccessView.as_view(), name= 'guardado'),
    path('eliminado/', views.vistaEliminada.as_view(), name= 'eliminado'),
    path('update-empleado/<pk>/', views.EmpleadoUpdateView.as_view(), name= 'modificar_empleado'),
    path('delete-empleado/<pk>/', views.EmpleadoDeleteView.as_view(), name= 'eliminar_empleado'),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyectoWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from aplicaciones.home. views import IndexView
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('', include('aplicaciones.home.urls')),
    path('', include('aplicaciones.empleados.urls')),
    path('', include('aplicaciones.departamento.urls')),
]

aplicaciones/empleados/models.py
from django.db import models
from aplicaciones.departamento.models import Departamento
from django_ckeditor_5.fields import CKEditor5Field

class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)

    class meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades Empleados'
    def __str__(self):
        return str(self.id) + '-' + self.habilidad

# Create your models here.
class Empleado(models.Model):
    """Modelo para tabla empleado"""
    JOB_CHOICE = (
        ('0','CONTADOR'),
        ('1','ADMINISTRADOR'),
        ('2','ECONOMISTA'),
        ('3','OTRO'),
    )

    first_name = models.CharField('Nombre', max_length=60)
    last_name = models.CharField('Apellidos', max_length=60)
    full_name = models.CharField('Nombre Completo', max_length=120, blank=True)
    job = models.CharField('Trabajo',max_length=50, choices=JOB_CHOICE)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='empleado', blank = True, null = True)
    habilidades = models.ManyToManyField('habilidades')
    hoja_vida = CKEditor5Field('Hoja de Vida', config_name='extends')

    class Meta:
        verbose_name = 'Mi Empleado'
        verbose_name_plural = 'Empleados de la empresa'
        ordering = ['-first_name','last_name']
        unique_together = ('first_name', 'departamento')

    def __str__(self):
        return str(self.id) + '-' + self.first_name + '-' + self.last_name

templates/persona/add.html
{% extends 'base.html' %}

{% block titulo %}
Añadir Nuevo
{% endblock titulo %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar empleado</h1>
        <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}
            <div class="medium-6 cell">
                <label>Nombres:
                    {{form.first_name}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Apellidos:
                    {{form.last_name}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Trabajo:
                    {{form.job}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Departamento:
                    {{form.departamento}}
                </label>
            </div>
            <div class="medium-12 cell">
                <label>Habilidades:
                    {{form.habilidades}}
                </label>
            </div>
            <div class="medium-12 cell">
                <label>Foto:
                    {{form.avatar}}
                </label>
            </div>
            <div class="medium-6 cell">
                <button type="submit" class="button success">Agregar</button>

            </div>


        </form>
    </div>
</div>

{% endblock content %}

templates/persona/by_kword.html
<h1>Buscar Empleado por palabra clave</h1>
<form method="GET">{% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="Ingrese nombre aquí">
    <button type="submit">Buscar</button>
</form>

<h3>Lista resultado</h3>
<ul>
    {% for e in empleados %}
        <li>{{e}}</li>
    {% endfor%}
</ul>

templates/persona/delete.html
{% extends 'base.html' %}


{% block titulo %}
Eliminar Empleado
{% endblock titulo %}

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Eliminar: {{object.first_name}}</h1>
        <form class="cell" method="POST">{% csrf_token %}
            <div class="callout secondary">
                <h5>Desea eliminar este empleado?</h5>
                <button type="submit" class="button alert">Confirmar </button>
                
            </div>
        </form>
    </div>
</div>

{% endblock content %}

templates/persona/detail_empleado.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}
{{object.full_name}}
{% endblock titulo %}



{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x grid-margin-x align-center">
        <div class="cell large-4 card" style="width: 300px;">
            <div class="card-divider">
                {{empleado.get_job_display}}
            </div>

            {% if empleado.avatar %}
                <img src="{{empleado.avatar.url}}">
            {% else %}
            <img src="{% static 'img/imagen_1.jpg' %}" alt="">
            {% endif %}


            <div class="card-section">
                <h4>{{empleado.full_name}}</h4>
                <p>{{empleado.fist_name}}</p>
                <p>{{empleado.last_name}}</p>
                <p>{{empleado.departamento.short_name}}</p>
                <p><span class="label">Habilidades: </span></p>
                <ul class="vertical menu">
                    {% for h in empleado.habilidades.all  %}
                       <li>{{h.habilidad}}</li> 
                    {% endfor %}
                </ul>
                
            </div>
        </div>

    </div>
</div>



{% endblock content %}

templates/persona/eliminado.html
<h1>El registro se elimino correctamente</h1>

templates/persona/habilidades.html
<h1>Habilidades de Empleado</h1>
    <ul>

        {% for h in habilidades %}
            <li>{{ h }}</li>
        {% endfor %}

    </ul>

templates/persona/list_all.html
{% extends 'base.html' %}


{% block titulo %}
    Lista de Todos los Empleados
{% endblock titulo %}
    

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista de todos los Empleados</h1>
        <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
            <div class="cell large-7">
                <input type="text" id="kword" name="kword" placeholder="Buscar empleado">
            </div>
            <div class="cell large-2">
                <button type="submit" class="submit success button">Buscar</button>
            </div>

        </form>
        <div class="cell">
            <ul>
                <table>
                    <thead>
                        <tr>
                            <th width="200">Id</th>
                            <th>Nombre</th>
                            <th width="150">Apellidos</th>
                            <th width="150">Departamento</th>
                            <th width="150">Acción</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for e in empleados %}
                        <tr>
                            console.log(e)
                            <td>{{e.id}}</td>
                            <td>{{e.first_name}}</td>
                            <td>{{e.last_name}}</td>
                            <td>{{e.departamento}}</td>
                            <td><a class="button warning" href="{% url 'persona_app:ver-empleado' e.id %}">Ver</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

            </ul>
        </div>
        <div class="cell">
            
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">
                    
                    {% if page_obj.has_previous %}
                        <li class="pagination-previous">
                            <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                        </li>
                    {% endif %}
                    
                    {% for pagina in paginator.page_range  %}
                    
                        {% if pagina == page_obj.number %}
                        <li class="current"><span class="show-for-sr">You're on page</span> {{pagina}}</li>
                        {% else %}
                        <li><a href="?page={{pagina}}">{{pagina}}</a></li>
                        {% endif %}
                        
  
                        
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="pagination-next">
                            <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
                
            {% endif %}
                
            
        </div>
    </div>



</div>

{% endblock content %}

templates/persona/list_by_area.html
{% extends 'base.html' %}


{% block titulo %}
Lista Empleados por departamento
{% endblock titulo %}


{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <div class="cell">Empleados por Area: </div>
        <div class="cell"></div>
        <table>
            <thead>
                <tr>
                    <th width="200">Id</th>
                    <th>Nombre</th>
                    <th width="150">Apellidos</th>
                    <th width="150">Departamento</th>
                    <th width="150">Acción</th>
                </tr>
            </thead>
            <tbody>
                {% for e in empleados %}
                <tr>
                    <td>{{e.id}}</td>
                    <td>{{e.first_name}}</td>
                    <td>{{e.last_name}}</td>
                    <td>{{e.departamento}}</td>
                    <td><a class="button warning" href="{% url 'persona_app:ver-empleado' e.id %}">Ver</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

</div>

{% endblock content %}

templates/persona/lista_empleados.html
{% extends 'base.html' %}


{% block titulo %}
    Lista de Todos los Empleados
{% endblock titulo %}
    

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista de todos los Empleados</h1>
        
        <div class="cell">
            <ul>
                <table>
                    <thead>
                        <tr>
                            <th width="200">Id</th>
                            <th>Nombre</th>
                            <th width="150">Apellidos</th>
                            <th width="150">Departamento</th>
                            <th width="150">Acción</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for e in empleados %}
                        <tr>
                            console.log(e)
                            <td>{{e.id}}</td>
                            <td>{{e.first_name}}</td>
                            <td>{{e.last_name}}</td>
                            <td>{{e.departamento}}</td>
                            <td>
                                <a class="button success" href="{% url 'persona_app:modificar_empleado' e.id %}">Editar</a>
                            </td>
                            <td>
                                <a class="button warning" href="{% url 'persona_app:eliminar_empleado' e.id %}">Eliminar</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

            </ul>
        </div>
        <div class="cell">
            
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">
                    
                    {% if page_obj.has_previous %}
                        <li class="pagination-previous">
                            <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                        </li>
                    {% endif %}
                    
                    {% for pagina in paginator.page_range  %}
                    
                        {% if pagina == page_obj.number %}
                        <li class="current"><span class="show-for-sr">You're on page</span> {{pagina}}</li>
                        {% else %}
                        <li><a href="?page={{pagina}}">{{pagina}}</a></li>
                        {% endif %}
                        
  
                        
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="pagination-next">
                            <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
                
            {% endif %}
                
            
        </div>
    </div>



</div>

{% endblock content %}

templates/persona/success.html
<h1>Felicitaciones, se guardó correctamente el empleado</h1>

templates/persona/update.html
{% extends 'base.html' %}


{% block titulo %}
Editar Empleado
{% endblock titulo %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Modificar Datos Empleados</h1>
        <div class="cell">
            <form method="POST">{% csrf_token %}
                <div class="grid-x grid-margin-x">
                <div class="large-6 cell">
                    <label>Nombre:
                        {{form.first_name}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Apellidos:
                        {{form.last_name}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Trabajo:
                        {{form.job}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Area:
                        {{form.departamento}}
                    </label>
                </div>
                <div class="large-6 cell">
                    <label>Habilidades Extra:
                        {{form.habilidades}}
                    </label>
                </div>
                </div>
                <button  type="submit" class="success button">Guardar</button>

            </form>
        </div>
    </div>

</div>
{% endblock content %}