aplicaciones/departamento/urls.py
from django.contrib import admin 
from django.urls import path


from . import views

app_name = 'departamento_app'

urlpatterns = [
    path('departamento-lista/', views.DepartamentoListView.as_view(), name='departamento_list'),
    path('new-departamento/', views.NewDepantamentoView.as_view(), name='nuevo_departamento'),
]

aplicaciones/empleados/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = "persona_app"

urlpatterns = [
    path('',views.InicioView.as_view(), name='inicio'),
    path('listar-todo-empleados/', views.ListAllEmpleados.as_view(), name='empleados_all'),
    path('listar-by-area/<shortname>', views.ListByAreaEmpleado.as_view(), name='empleados_area'),
    path('listar-empleados-admin/', views.ListaEmpleadosAdmin.as_view(), name='empleados_admin'),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('lista-habilidades-empleado/<id>', views.ListaHabilidadesEmpleado.as_view()),
    path('ver-empleado/<pk>', views.EmpleadoDetailView.as_view(),name='ver-empleado'),  #El <pk> es como el id, se usa para obtener el id unico para identificar el registro
    path('add-empleado/', views.EmpleadoCreateView.as_view(), name='empleado_add'),
    path('success/', views.SuccessView.as_view(), name= 'guardado'),
    path('eliminado/', views.vistaEliminada.as_view(), name= 'eliminado'),
    path('update-empleado/<pk>/', views.EmpleadoUpdateView.as_view(), name= 'modificar_empleado'),
    path('delete-empleado/<pk>/', views.EmpleadoDeleteView.as_view(), name= 'eliminar_empleado'),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyectoWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from aplicaciones.home. views import IndexView
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('', include('aplicaciones.home.urls')),
    path('', include('aplicaciones.empleados.urls')),
    path('', include('aplicaciones.departamento.urls')),
]

aplicaciones/departamento/models.py
from django.db import models

# Create your models here.
class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=50)
    short_name = models.CharField('Nombre Corto', max_length=20)
    anulate = models.BooleanField('Anulado', default=False) 

    class Meta:
        verbose_name = 'Mi Departamento'
        verbose_name_plural = "Areas de la empresa"
        ordering = ['name']
        unique_together = ('name','short_name')

    
    def __str__(self):
        return str(self.id) + '-' + self.name + '-' + self.short_name

aplicaciones/departamento/forms.py
from django import forms

class NewDepantamentoForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shortname = forms.CharField(max_length=20)

aplicaciones/departamento/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import FormView
# Create your views here.
from .forms import NewDepantamentoForm

from aplicaciones.empleados.models import Empleado
from aplicaciones.departamento.models import Departamento


class DepartamentoListView(ListView):
    model = Departamento
    template_name = "departamento/lista.html"
    context_object_name = 'departamentos'



class NewDepantamentoView(FormView):
    template_name = 'departamento/new_departamento.html'
    form_class = NewDepantamentoForm
    success_url = '/'

    def form_valid(self, form):
        depa = Departamento(
            name = form.cleaned_data['departamento'],
            short_name=form.cleaned_data['shortname']
        )
        depa.save()     #para agregar de esta forma, hay que utilizar este metodo de .save()

        nombre = form.cleaned_data['nombre']
        apellido = form.cleaned_data['apellidos']
        Empleado.objects.create(    #utilizando este metodo se agrega automaticamente con .create()
            first_name = nombre,
            last_name = apellido,
            job='1',
            departamento=depa
        )
        return super(NewDepantamentoView, self).form_valid(form)

templates/departamento/lista.html
{% extends 'base.html' %}

{% block titulo %}
    Lista Departamento
{% endblock titulo %}


{% block content %}
    {% include 'includes/header.html' %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista Departamentos</h1>
            <div class="cell">
                <table>
                    <tbody>
                        
                        {% for departamentos in departamentos %}
                        <tr>
                            <td>{{departamentos.name}}</td>
                            <td>{{departamentos.short_name}}</td>
                            <td><a class="button warning" href="{% url 'persona_app:empleados_area' departamentos.short_name %}">Ver Empleados</a></td>
                        </tr>
                        {% endfor %}
                            
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    
{% endblock content %}
    

templates/departamento/new_departamento.html
{% extends 'base.html' %}

{% block titulo %}
Registrar Departamento
{% endblock titulo %}


{% block content %}

{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar Departamento</h1>
        <form class="cell callout grid-x grid-margin-x" method="POST">{% csrf_token %}
            <div class="medium-6 cell">
                <label for="">Nombres:</label>
                {{form.nombre}}
            </div>
            <div class="medium-6 cell">
                <label for="">Apellidos:</label>
                {{form.apellidos}}
            </div>
            <div class="medium-6 cell">
                <label for="">Departamento:</label>
                {{form.departamento}}
            </div>
            <div class="medium-6 cell">
                <label for="">Nombre Corto:</label>
                {{form.shortname}}
            </div>
            
            <button class="button success" type="submit">Guardar</button>
        </form>
    </div>
</div>


{% endblock content %}